### ISSUE TITLE
目前是否支持简谱->je谱的转换

### ISSUE THREAD

**Issue by orikey0** [madderscientist/je_score_operator#1]

**Comment by madderscientist** [comment]
> _No description provided._

你说的是ocr吗？我认为在前端难以实现。
如果你有好的实现方法，欢迎交流

**Comment by orikey0** [comment]
> > _No description provided._
> 
> 你说的是ocr吗？我认为在前端难以实现。 如果你有好的实现方法，欢迎交流

对，我之前做过类似的功能，但是乐谱的提取上，和平常的ocr相比还是比较难的，这里面有些工作，我可以做一部分，具体可以功能点的视线可以参考这个专利流程，后端的部分工作可以给我来，但是因为我主要是做后端的，算法部分可能偏弱，不知道dalao是否有兴趣一起把功能拆分搞搞。https://patents.google.com/patent/CN102663423A/zh

**Comment by orikey0** [comment]
> > > _No description provided._
> > 
> > 
> > 你说的是ocr吗？我认为在前端难以实现。 如果你有好的实现方法，欢迎交流
> 
> 对，我之前做过类似的功能，但是乐谱的提取上，和平常的ocr相比还是比较难的，这里面有些工作，我可以做一部分，具体可以功能点的视线可以参考这个专利流程，后端的部分工作可以给我来，但是因为我主要是做后端的，算法部分可能偏弱，不知道dalao是否有兴趣一起把功能拆分搞搞。https://patents.google.com/patent/CN102663423A/zh

https://github.com/orikey0/QinJianPu 后端ocr的话 目前初步打算参考这个，在这个基础上看看还有没有更好的ocr包能直接用

**Comment by madderscientist** [comment]
提取原理大同小异，算法都很简单（容易理解），但是实际应用的效果很难保证（尝试本仓库的五线谱识别时我深刻感受到这点），需要长时间的调参测试。
我的偏好是纯前端造轮子，简谱提取的流程和算法计算量偏大，不适合纯前端；考虑到开发效率也不会造轮子，因此原理技术上对我的吸引并不大。但如果你想实现，你可以另开一个项目，我为你打下手。关于我的技术栈，Java浅尝辄止，后端只会用nodejs或者python。（也许并不能帮上忙？）

关于这份专利，有很多槽点：
1. 用二分的SVM区分似乎并不适合，也许直接用多分类的神经网络会更合适？
2. 提取结束后的播放，明显用合成器原理实现更合适，却用了自己采集的wav文件播放，效果不会好。
3. 识别结果直接做成midi就好了，弄成他的格式是作茧自缚。做成midi也不需要自己采样音色，处理工具也更成熟。
4. 自动加鼓点、加重拍是在牛粪上做点缀。总之“步骤三：数字音频的生成及播放”从根基上就走偏了。

另，对比“图片简谱”到je谱（或者midi），我更想实现“音频文件”到midi，这也是我最近在写的项目。但无论是哪个方向，我认为对于非AI方法，都需要人工的介入（无论是开发时参数的调整，还是使用时用户的纠正）才能保证正确率。设计时可以添加人工修正的流程。这点在目前五线谱识别我认为最好的项目中有所体现，你可以稍作了解，也许能提供一些改进的思路：https://github.com/Audiveris/audiveris


> 对，我之前做过类似的功能，但是乐谱的提取上，和平常的ocr相比还是比较难的，这里面有些工作，我可以做一部分，具体可以功能点的视线可以参考这个专利流程，后端的部分工作可以给我来，但是因为我主要是做后端的，算法部分可能偏弱，不知道dalao是否有兴趣一起把功能拆分搞搞。https://patents.google.com/patent/CN102663423A/zh

**Comment by orikey0** [comment]
> 前端；考虑到开发效率也不会造轮子，因此原理技术上对我的吸引并不大。但如果你想实现，你可以另开一个项目，

哈哈，你说的这些细节，我基本上是认可的。

因为对于我个人来说 我几乎完全不懂乐理。我从个人需求上出发，我最迫切的需求场景是，我找到一首歌，没有 fe谱/需要转调 ，但是可以在网上只能找到一份简谱，然后将这份简谱直接上传网站，你返回给我一个开箱就能用的fe谱就可以了，当然输出成为midi格式，再从midi转fe是更方便的一种。

至于专利部分，只是随便搜索一下，找了一下相关方案，没有细化调研。对于你给的这个audiveris我曾在前面调研的时候，在知乎上看到过一些介绍。我可能会在未来的一个月内周末陆陆续续调研+出一份技术方案，如果dalao有时间的话，**可以一起过一下技术方案**。
至于语言的选型上，我个人是python java go rust c++都可，nodejs是真的没看过，但是根据我工作换语言的经验来说，这应该是最微不足道的事情之一。音频文件到midi格式，我个人感觉对我来讲，吸引力反而不够大，主要原因是个人乐理知识无限接近0，甚至五线谱都看不明白，如果只是为了满足上述所说的场景，我个人认为已经能满足像我这样的小白用户的大部分场景了。
最后如果方便的话，可以加一下绿色软件后面可以一起探讨一下base64:TElIT1VIVUFMSUhBTw==

**Comment by madderscientist** [comment]
学生一个，dalao不敢当。期待从你这学到东西。
在我的心目中midi是最优秀的中转格式。对于小白，当然最好还是要一个能听的东西作为参考吧？
申请已发，如果平台没错且没解错的话。

> 对于你给的这个audiveris我曾在前面调研的时候，在知乎上看到过一些介绍。

刚刚去知乎搜了一下，你看到的大概就是我写的文……

> 但是可以在网上只能找到一份简谱

这大概是找谱经验不够……这种情况下我会去找midi再转，很少失手。
